name: Deploy PR build

on:
  pull_request:
    types: [opened, synchronize]

env:
  PROJECT_ID: scouting-1ce7e
  REGION: us-east1

jobs:
  deploy:

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.gcp_auth }}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: scouting-pr-${{ github.event.pull_request.number }}
          region: ${{ env.REGION }}
          source: ./
          flags: "--allow-unauthenticated"

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
